import express from 'express';
import { apiKeyService } from '../services/apiKeyService.js';
import { dataStore } from '../services/dataStore.js';
import { requireApiKey } from '../middleware/auth.js';

const router = express.Router();

/**
 * POST /api/keys/generate
 * Generate a new API key for the current user/device
 * Requires: x-api-key header (parent key validation)
 * Body: { name: string, deviceName?: string }
 */
router.post('/generate', requireApiKey, async (req, res, next) => {
    try {
        const { name, deviceName } = req.body;

        // Validation
        if (!name || typeof name !== 'string' || name.trim().length === 0) {
            return res.status(400).json({
                error: 'Invalid key name. Must be a non-empty string.',
            });
        }

        if (
            deviceName &&
            (typeof deviceName !== 'string' || deviceName.trim().length > 255)
        ) {
            return res.status(400).json({
                error: 'Invalid device name. Must be a string with max 255 characters.',
            });
        }

        // Get the API key info from the request
        const createdBy =
            req.apiKey?.id || req.apiKey?.createdBy || 'unknown-user';

        const result = await apiKeyService.generateKey(
            name.trim(),
            deviceName?.trim() || null,
            createdBy
        );

        console.log(`📝 New API key generated by ${createdBy}: ${name}`);

        res.status(201).json({
            success: true,
            message: 'API key generated successfully',
            data: result,
        });
    } catch (error) {
        console.error('❌ Error generating API key:', error);
        next(error);
    }
});

/**
 * GET /api/keys
 * List all API keys for the current user/device
 * Requires: x-api-key header
 * Query: ?includeInactive=false (optional)
 */
router.get('/', requireApiKey, async (req, res, next) => {
    try {
        const { includeInactive } = req.query;
        const createdBy =
            req.apiKey?.id || req.apiKey?.createdBy || 'unknown-user';

        // Get user's keys
        const keys = await apiKeyService.listUserKeys(createdBy);

        if (!keys) {
            return res.json({
                success: true,
                data: [],
                message: 'No API keys found',
            });
        }

        // Filter inactive if needed
        let filteredKeys = keys;
        if (includeInactive !== 'true') {
            filteredKeys = keys.filter((k) => k.isActive);
        }

        // Never return the actual key values to the client
        const safeKeys = filteredKeys.map((k) => ({
            id: k.id,
            name: k.name,
            deviceName: k.deviceName,
            lastUsedAt: k.lastUsedAt,
            createdAt: k.createdAt,
            isActive: k.isActive,
            keyPreview: `${k.key.substring(0, 10)}...`, // Only show first 10 chars
        }));

        res.json({
            success: true,
            data: safeKeys,
            total: safeKeys.length,
        });
    } catch (error) {
        console.error('❌ Error listing API keys:', error);
        next(error);
    }
});

/**
 * GET /api/keys/stats
 * Get API key statistics
 * Requires: x-api-key header
 */
router.get('/stats', requireApiKey, async (req, res, next) => {
    try {
        const stats = await dataStore.getApiKeyStats();

        res.json({
            success: true,
            data: stats,
        });
    } catch (error) {
        console.error('❌ Error getting API key stats:', error);
        next(error);
    }
});

/**
 * DELETE /api/keys/:id
 * Deactivate/delete an API key
 * Requires: x-api-key header
 * The key can only delete their own keys
 */
router.delete('/:id', requireApiKey, async (req, res, next) => {
    try {
        const { id } = req.params;
        const createdBy =
            req.apiKey?.id || req.apiKey?.createdBy || 'unknown-user';

        if (!id || id.trim().length === 0) {
            return res.status(400).json({
                error: 'Invalid key ID',
            });
        }

        // Get all user's keys to verify ownership
        const userKeys = await apiKeyService.listUserKeys(createdBy);
        const keyExists = userKeys?.some((k) => k.id === id);

        if (!keyExists) {
            return res.status(403).json({
                error: 'You do not have permission to delete this key',
            });
        }

        // Deactivate the key (soft delete for audit trail)
        await apiKeyService.deactivateKey(id);

        console.log(`🗑️ API key deactivated: ${id} by ${createdBy}`);

        res.json({
            success: true,
            message: 'API key deactivated successfully',
        });
    } catch (error) {
        console.error('❌ Error deactivating API key:', error);
        next(error);
    }
});

/**
 * POST /api/keys/validate
 * Validate an API key (for testing purposes)
 * Body: { key: string }
 */
router.post('/validate', async (req, res, next) => {
    try {
        const { key } = req.body;

        if (!key || typeof key !== 'string') {
            return res.status(400).json({
                error: 'Invalid key provided',
            });
        }

        const result = await apiKeyService.validateKey(key);

        if (result.valid) {
            res.json({
                success: true,
                message: 'API key is valid',
                data: {
                    id: result.id,
                    name: result.name,
                    deviceName: result.deviceName,
                    lastUsedAt: result.lastUsedAt,
                },
            });
        } else {
            res.status(401).json({
                success: false,
                message: 'API key is invalid',
                reason: result.reason,
            });
        }
    } catch (error) {
        console.error('❌ Error validating API key:', error);
        next(error);
    }
});

export default router;
